[package]
name = "ctsi_sol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "^0.25.0"
anchor-spl = "^0.25.0"
spl-associated-token-account = "^1.0.5"
