[features]
seeds = false
[programs.localnet]
solzen = "2QB8wEBJ8jjMQuZPvj3jaZP7JJb5j21u4xbxTnwsZRfv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "localnet"
# cluster = "devnet"
cluster = "testnet"
wallet = "/Users/oshiro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
