[package]
name = "eth-signature-verify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
libsecp256k1 = "0.7.1"
sha3 = "0.10.5"
